# Auto-generated from the NS OpenAPI spec. Do not edit manually.
# To regenerate, run: uv run scripts/generate_models.sh
#
# generated by datamodel-codegen:
#   filename:  disruptions-api.json
#   timestamp: 2026-02-24T14:54:35+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Type(StrEnum):
    disruption = 'DISRUPTION'
    maintenance = 'MAINTENANCE'


class Impact(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    value: Any = Field(..., title='Impact.value')


class Phase(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str = Field(..., title='Phase.id')
    label: str = Field(..., title='Phase.label')


class TitleSectionType(StrEnum):
    station = 'STATION'
    icon = 'ICON'


class ExpectedDuration(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    description: str = Field(..., title='ExpectedDuration.description')
    """
    Human-readable description of the expected duration of the disruption.
    """
    end_time: str | None = Field(
        None, alias='endTime', title='ExpectedDuration.endTime'
    )
    """
    Expected end time for this disruption
    """


class Situation(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    label: str = Field(..., title='TimeSpan.situation.label')
    """
    "Human readable description of the situation caused by the disruption
    """


class CauseType(StrEnum):
    disrupted_later_today = 'DISRUPTED_LATER_TODAY'
    other = 'OTHER'


class AdditionalTravelTime(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    label: str = Field(..., title='AdditionalTravelTime.label')
    """
    Human-readable description of the additional travel time that is expected"
    """
    short_label: str | None = Field(
        None, alias='shortLabel', title='AdditionalTravelTime.shortLabel'
    )
    """
    Short human-readable description of the additional travel time that is expected
    """
    minimum_duration_in_minutes: float | None = Field(
        None,
        alias='minimumDurationInMinutes',
        title='AdditionalTravelTime.minimumDurationInMinutes',
    )
    """
    Minimum expected additional travel time in minutes
    """
    maximum_duration_in_minutes: float | None = Field(
        None,
        alias='maximumDurationInMinutes',
        title='AdditionalTravelTime.maximumDurationInMinutes',
    )
    """
    Maximum expected additional travel time in minutes
    """


class AlternativeTransportSummary(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    label: str = Field(..., title='AlternativeTransportSummary.label')
    """
    Human-readable description of the alternative transport that is available to the user
    """
    short_label: str | None = Field(
        None, alias='shortLabel', title='AlternativeTransportSummary.shortLabel'
    )
    """
    Short label indicating the alternative transport that is available to the user
    """


class SectionDirection(StrEnum):
    one_way = 'ONE_WAY'
    both = 'BOTH'


class Coordinate(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    lat: float = Field(..., title='Coordinate.lat')
    lng: float = Field(..., title='Coordinate.lng')


class DisruptionLevel(StrEnum):
    no_or_much_less_trains = 'NO_OR_MUCH_LESS_TRAINS'
    less_trains = 'LESS_TRAINS'
    normal_or_more_trains = 'NORMAL_OR_MORE_TRAINS'


class SectionType(StrEnum):
    nl = 'NL'
    neighboring_country = 'NEIGHBORING_COUNTRY'
    hsl = 'HSL'
    international = 'INTERNATIONAL'


class Type1(StrEnum):
    calamity = 'CALAMITY'


class Type2(StrEnum):
    download = 'DOWNLOAD'


class Type3(StrEnum):
    links = 'LINKS'


class Type4(StrEnum):
    text = 'TEXT'


class TextBodyItemContent(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    text: str | None = Field(None, title='TextBodyItemContent.text')


class Link(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    title: str | None = Field(None, title='Link.title')
    url: str | None = Field(None, title='Link.url')


class Download(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    title: str | None = Field(None, title='Download.title')
    url: str | None = Field(None, title='Download.url')
    content_length: float = Field(
        ..., alias='contentLength', title='Download.contentLength'
    )
    mime_type: str | None = Field(None, alias='mimeType', title='Download.mimeType')
    last_modified: str | None = Field(
        None, alias='lastModified', title='Download.lastModified'
    )


class ButtonPosition(StrEnum):
    top = 'TOP'
    bottom = 'BOTTOM'


class ButtonType(StrEnum):
    planner = 'PLANNER'
    disruptions = 'DISRUPTIONS'
    maintenance = 'MAINTENANCE'
    external = 'EXTERNAL'


class CalamityPriority(StrEnum):
    prio_1 = 'PRIO_1'
    prio_2 = 'PRIO_2'
    prio_3 = 'PRIO_3'


class DisruptionType(StrEnum):
    calamity = 'CALAMITY'
    disruption = 'DISRUPTION'
    maintenance = 'MAINTENANCE'


class Priority(StrEnum):
    prio_1 = 'PRIO_1'
    prio_2 = 'PRIO_2'
    prio_3 = 'PRIO_3'


class RepeatOn(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    monday: bool = Field(..., title='SyncSavedTripsRequest.repeatOn.monday')
    tuesday: bool = Field(..., title='SyncSavedTripsRequest.repeatOn.tuesday')
    wednesday: bool = Field(..., title='SyncSavedTripsRequest.repeatOn.wednesday')
    thursday: bool = Field(..., title='SyncSavedTripsRequest.repeatOn.thursday')
    friday: bool = Field(..., title='SyncSavedTripsRequest.repeatOn.friday')
    saturday: bool = Field(..., title='SyncSavedTripsRequest.repeatOn.saturday')
    sunday: bool = Field(..., title='SyncSavedTripsRequest.repeatOn.sunday')


class SyncSavedTripsRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: float = Field(..., title='SyncSavedTripsRequest.id')
    ctx_recon: str = Field(
        ..., alias='ctxRecon', title='SyncSavedTripsRequest.ctxRecon'
    )
    current_ctx_recon: str = Field(
        ..., alias='currentCtxRecon', title='SyncSavedTripsRequest.currentCtxRecon'
    )
    repeat_on: RepeatOn = Field(
        ..., alias='repeatOn', title='SyncSavedTripsRequest.repeatOn'
    )


class SyncSavedTrips(RootModel[Any]):
    root: Any = Field(..., title='SyncSavedTrips')


class Type5(StrEnum):
    saved_trip = 'SAVED_TRIP'


class Type6(StrEnum):
    trip = 'TRIP'


class AffectingDisruptionType(StrEnum):
    disruption = 'DISRUPTION'
    maintenance = 'MAINTENANCE'


class TitleSection(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    type: TitleSectionType
    value: str = Field(..., title='TitleSection.value')


class Cause(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    label: str = Field(..., title='Cause.label')
    """
    Human-readable description of the disruption cause
    """
    type: CauseType


class StationReference(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    uic_code: str = Field(..., alias='uicCode', title='StationReference.uicCode')
    """
    Short UIC code for this station
    """
    station_code: str | None = Field(
        None, alias='stationCode', title='StationReference.stationCode'
    )
    """
    Short station code (e.g. UT for Utrecht Centraal)
    """
    name: str = Field(..., title='StationReference.name')
    """
    Long name of this station
    """
    coordinate: Coordinate | None = None
    country_code: str = Field(
        ..., alias='countryCode', title='StationReference.countryCode'
    )
    """
    Country code of the country that this station is in.

    e.g. NL, D, B, F
    """


class Location(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    station: StationReference
    description: str = Field(..., title='Location.description')
    """
    Human-readable description of the location of the alternative transport
    """


class Button(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    label: str | None = Field(None, title='Button.label')
    type: ButtonType | None = None
    accessibility_label: str | None = Field(
        None, alias='accessibilityLabel', title='Button.accessibilityLabel'
    )
    url: str | None = Field(None, title='Button.url')


class TextAndMediaBodyItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    title: str | None = Field(None, title='TextAndMediaBodyItem.title')
    type: Type4 = Field(..., title='TextAndMediaBodyItem.type')
    content: TextBodyItemContent


class LinksBodyItemContent(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    links: list[Link] = Field(..., title='LinksBodyItemContent.links')


class DownloadsBodyItemContent(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    downloads: list[Download] = Field(..., title='DownloadsBodyItemContent.downloads')


class BaseDisruption(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str = Field(..., title='BaseDisruption.id')
    type: DisruptionType
    is_active: bool = Field(..., alias='isActive', title='BaseDisruption.isActive')
    title: str = Field(..., title='BaseDisruption.title')
    topic: str | None = Field(None, title='BaseDisruption.topic')


class AffectingDisruption(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str = Field(..., title='AffectingDisruption.id')
    type: AffectingDisruptionType


class TimeSpan(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    start: str = Field(..., title='TimeSpan.start')
    """
    Start time of this timespan
    """
    end: str | None = Field(None, title='TimeSpan.end')
    """
    End time of this timespan. May be left empty if unknown
    """
    period: str | None = Field(None, title='TimeSpan.period')
    """
    Human-readable description of the period for this disruption
    """
    situation: Situation = Field(..., title='TimeSpan.situation')
    """
    Information about the situation caused by the disruption
    """
    cause: Cause | None = None
    additional_travel_time: AdditionalTravelTime | None = Field(
        None, alias='additionalTravelTime'
    )
    alternative_transport: AlternativeTransportSummary | None = Field(
        None, alias='alternativeTransport'
    )
    advices: list[str] = Field(..., title='TimeSpan.advices')
    """
    List of advices
    """


class Section(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    stations: list[StationReference] = Field(..., title='Section.stations')
    direction: SectionDirection | None = None
    operators: list[str] = Field(..., title='Section.operators')


class DisruptionConsequence(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    section: Section
    description: str | None = Field(None, title='DisruptionConsequence.description')
    level: DisruptionLevel


class AlternativeTransport(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    location: list[Location] = Field(..., title='AlternativeTransport.location')
    """
    Gives more information about the location of the alternative transport
    """
    label: str = Field(..., title='AlternativeTransport.label')
    """
    Human-readable description of the alternative transport that is available to the user
    """
    short_label: str | None = Field(
        None, alias='shortLabel', title='AlternativeTransport.shortLabel'
    )
    """
    Short label indicating the alternative transport that is available to the user
    """


class Buttons(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    position: list[ButtonPosition] = Field(..., title='Buttons.position')
    items: list[Button] = Field(..., title='Buttons.items')


class DownloadsBodyItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    title: str | None = Field(None, title='DownloadsBodyItem.title')
    type: Type2 = Field(..., title='DownloadsBodyItem.type')
    content: DownloadsBodyItemContent


class LinksBodyItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    title: str | None = Field(None, title='LinksBodyItem.title')
    type: Type3 = Field(..., title='LinksBodyItem.type')
    content: LinksBodyItemContent


class PersonalDisruptionSavedTripItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    type: Type6 = Field(..., title='PersonalDisruptionSavedTripItem.type')
    ctx_recon: str = Field(
        ..., alias='ctxRecon', title='PersonalDisruptionSavedTripItem.ctxRecon'
    )
    from_date_time: str = Field(
        ..., alias='fromDateTime', title='PersonalDisruptionSavedTripItem.fromDateTime'
    )
    arrival_date_time: str = Field(
        ...,
        alias='arrivalDateTime',
        title='PersonalDisruptionSavedTripItem.arrivalDateTime',
    )
    affecting_disruptions: list[AffectingDisruption] = Field(
        ...,
        alias='affectingDisruptions',
        title='PersonalDisruptionSavedTripItem.affectingDisruptions',
    )


class PublicationSection(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    section: Section
    consequence: DisruptionConsequence | None = None
    section_type: SectionType = Field(..., alias='sectionType')


class AlternativeTransportTimeSpan(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    start: str = Field(..., title='AlternativeTransportTimeSpan.start')
    """
    Start time of this timespan
    """
    end: str | None = Field(None, title='AlternativeTransportTimeSpan.end')
    """
    End time of this timespan
    """
    alternative_transport: AlternativeTransport = Field(
        ..., alias='alternativeTransport'
    )


class BodyItem(RootModel[DownloadsBodyItem | LinksBodyItem | TextAndMediaBodyItem]):
    root: DownloadsBodyItem | LinksBodyItem | TextAndMediaBodyItem = Field(
        ..., title='BodyItem'
    )


class PersonalDisruption(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    registration_id: str = Field(
        ..., alias='registrationId', title='PersonalDisruption.registrationId'
    )
    trips: list[PersonalDisruptionSavedTripItem] = Field(
        ..., title='PersonalDisruption.trips'
    )
    type: Type5 = Field(..., title='PersonalDisruption.type')


class Disruption(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str = Field(..., title='id')
    """
    Unique identifier of the disruption
    """
    is_active: bool = Field(..., alias='isActive', title='isActive')
    """
    Whether this item is active, i.e. it is currently happening. For example maintenance that starts in the future has this property set to false
    """
    topic: str | None = Field(None, title='topic')
    """
    Topic to subscribe to in order to receive updates for this disruption.
    """
    title: str = Field(..., title='title')
    """
    Title of the disruption, containing the location(s) of the disruption
    """
    type: Type = Field(..., title='type')
    """
    Type of disruption
    """
    registration_time: str | None = Field(
        None, alias='registrationTime', title='registrationTime'
    )
    """
    Registration time of this disruption
    """
    release_time: str | None = Field(None, alias='releaseTime', title='releaseTime')
    """
    Release time of this disruption
    """
    local: bool = Field(..., title='local')
    """
    A local disruption has messages tailored towards a specific station.
    """
    title_sections: list[list[TitleSection]] = Field(
        ..., alias='titleSections', title='titleSections'
    )
    """
    Title of the disruption which includes where the disruption takes place. For example: Utrecht - Gouda -Icon- Den Haag
    """
    start: str | None = Field(None, title='start')
    """
    Start time of the disruption
    """
    end: str | None = Field(None, title='end')
    """
    End time of the disruption. May be left empty if unknown
    """
    period: str | None = Field(None, title='period')
    """
    Human-readable description of the period for this disruption
    """
    phase: Phase | None = None
    impact: Impact | None = None
    expected_duration: ExpectedDuration | None = Field(None, alias='expectedDuration')
    publication_sections: list[PublicationSection] = Field(
        ..., alias='publicationSections', title='publicationSections'
    )
    """
    Publication sections for these disruptions. Please note that these may be larger than the actual
    track sections where the disruption is. This has to do with stations being recognizable for the customer.
    For example, there could be a disruption between Utrecht Vaartse Rijn and Bunnik. In that case, the
    trajectory could be Utrecht Centraal to Driebergen-Zeist, as most customers do not know where Utrecht Vaartse
    Rijn and Bunnik are. In this case, the trajectory will contain Utrecht Centraal to Driebergen-Zeist, whereas
    the disruptedTrackSection will contain Utrecht Vaartse Rijn to Bunnik
    """
    timespans: list[TimeSpan] = Field(..., title='timespans')
    """
    Distinguishable timespans within this disruption. Multiple timespans may occur for maintenance.
    """
    alternative_transport_timespans: list[AlternativeTransportTimeSpan] = Field(
        ...,
        alias='alternativeTransportTimespans',
        title='alternativeTransportTimespans',
    )
    """
    Distinguishable timespans for alternative transport within this disruption.
    """
    summary_additional_travel_time: AdditionalTravelTime | None = Field(
        None, alias='summaryAdditionalTravelTime'
    )


class Calamity(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str = Field(..., title='id')
    """
    Unique identifier of the calamity
    """
    is_active: bool = Field(..., alias='isActive', title='isActive')
    """
    Whether calamity item is active, i.e. it is currently happening. For example maintenance that starts in the future has this property set to false
    """
    title: str = Field(..., title='title')
    """
    Title of the calamity
    """
    topic: str = Field(..., title='topic')
    """
    Topic to subscribe to in order to receive updates for this calamity.
    """
    type: Type1 = Field(..., title='type')
    """
    Type of disruption
    """
    description: str | None = Field(None, title='description')
    """
    Human-readable description for this calamity
    """
    priority: CalamityPriority
    last_updated: str | None = Field(None, alias='lastUpdated', title='lastUpdated')
    """
    Moment that this calamity was last updated
    """
    expected_next_update: str | None = Field(
        None, alias='expectedNextUpdate', title='expectedNextUpdate'
    )
    """
    Expected moment that this calamity will be updated
    """
    body_items: list[BodyItem] = Field(..., alias='bodyItems', title='bodyItems')
    """
    Body items to render when showing this calamity
    """
    buttons: Buttons
    url: str | None = Field(None, title='url')
    """
    URL for more information about this calamity
    """
