# generated by datamodel-codegen:
#   filename:  nsapp-stations-api.json
#   timestamp: 2026-02-24T15:57:15+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class StationIdentification(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    uic_code: str = Field(..., alias='uicCode')
    """
    Short UIC code for this station
    """
    uic_cd_code: str | None = Field(None, alias='uicCdCode')
    """
    Long UIC code for this station, if present
    """
    eva_code: str | None = Field(None, alias='evaCode')
    """
    EuroEVA code for this station, if present
    """
    cd_code: float | None = Field(None, alias='cdCode')
    """
    Short code that is used for price computations (MRP)
    """
    code: str | None = None
    """
    Short station code (e.g. UT for Utrecht Centraal)
    """


class StationTypeV3(StrEnum):
    local_train_station = 'LOCAL_TRAIN_STATION'
    local_train_hub_station = 'LOCAL_TRAIN_HUB_STATION'
    express_train_station = 'EXPRESS_TRAIN_STATION'
    express_train_hub_station = 'EXPRESS_TRAIN_HUB_STATION'
    intercity_station = 'INTERCITY_STATION'
    intercity_hub_station = 'INTERCITY_HUB_STATION'
    mega_station = 'MEGA_STATION'
    optional_station = 'OPTIONAL_STATION'


class StationNames(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    long: str
    medium: str
    short: str
    festive: str | None = None
    synonyms: list[str]
    """
    List of synonyms for this station
    """


class Coordinate(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    lat: float
    lng: float


class NearbyMeLocationId(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    value: str
    type: str


class Track(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    spoor_nummer: str = Field(..., alias='spoorNummer')


class StationTypeV2(StrEnum):
    stoptrein_station = 'STOPTREIN_STATION'
    knooppunt_stoptrein_station = 'KNOOPPUNT_STOPTREIN_STATION'
    sneltrein_station = 'SNELTREIN_STATION'
    knooppunt_sneltrein_station = 'KNOOPPUNT_SNELTREIN_STATION'
    intercity_station = 'INTERCITY_STATION'
    knooppunt_intercity_station = 'KNOOPPUNT_INTERCITY_STATION'
    mega_station = 'MEGA_STATION'
    facultatief_station = 'FACULTATIEF_STATION'


class StationsNamen(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    lang: str
    middel: str
    kort: str
    festive: str | None = None


class StationV2(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    uic_code: str = Field(..., alias='UICCode')
    uic_cd_code: str | None = Field(None, alias='UICCdCode')
    station_type: StationTypeV2 = Field(..., alias='stationType')
    eva_code: str | None = Field(None, alias='EVACode')
    cd_code: float | None = Field(None, alias='cdCode')
    code: str | None = None
    sporen: list[Track]
    synoniemen: list[str]
    heeft_faciliteiten: bool = Field(..., alias='heeftFaciliteiten')
    heeft_vertrektijden: bool = Field(..., alias='heeftVertrektijden')
    heeft_reisassistentie: bool = Field(..., alias='heeftReisassistentie')
    namen: StationsNamen | None = None
    land: str | None = None
    lat: float | None = None
    lng: float | None = None
    radius: float | None = None
    naderen_radius: float | None = Field(None, alias='naderenRadius')
    distance: float | None = None
    ingangs_datum: str | None = Field(None, alias='ingangsDatum')
    eind_datum: str | None = Field(None, alias='eindDatum')
    nearby_me_location_id: NearbyMeLocationId | None = Field(
        None, alias='nearbyMeLocationId'
    )


class StationsV2Response(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    payload: list[StationV2]


class StationV3(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: StationIdentification
    station_type: StationTypeV3 = Field(..., alias='stationType')
    names: StationNames
    location: Coordinate | None = None
    tracks: list[str]
    """
    List of tracks known to this station
    """
    has_known_facilities: bool = Field(..., alias='hasKnownFacilities')
    """
    Indicates whether this station has known facilities
    """
    available_for_accessible_travel: bool = Field(
        ..., alias='availableForAccessibleTravel'
    )
    """
    Indicates whether this station is available for accessible travel (i.e. has travel assistance or tracks that are independently accessible)
    """
    has_travel_assistance: bool = Field(..., alias='hasTravelAssistance')
    """
    Indicates that NSRA (NS Reisassistentie) is available at this station
    """
    are_tracks_independently_accessible: bool = Field(
        ..., alias='areTracksIndependentlyAccessible'
    )
    """
    Indicates that the tracks at this station are accessible without assistance. Please note that when the train itself is not accessible without assistance, the traveller still needs assistance.
    """
    is_border_stop: bool = Field(..., alias='isBorderStop')
    """
    Indicates whether this station is only used to mark a border between two countries
    """
    country: str
    """
    Country that this station is in
    """
    radius: float | None = None
    """
    Radius around the exact location of the station where a someone is considered to be at the station
    """
    approaching_radius: float | None = Field(None, alias='approachingRadius')
    """
    Radius around a station where a train is considered to be approaching the station
    """
    distance: float | None = None
    """
    Distance in meters to a requested coordinate (latitude, longitude)
    """
    start_date: str | None = Field(None, alias='startDate')
    """
    Start date for this station (ISO Format). If not set, the date is unknown and the station is supposed to be opened
    """
    end_date: str | None = Field(None, alias='endDate')
    """
    End date for this station (ISO Format). If not set, the date is unknown and the station is supposed to be opened.
    """
    nearby_me_location_id: NearbyMeLocationId | None = Field(
        None, alias='nearbyMeLocationId'
    )


class StationsV3Response(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    payload: list[StationV3]


class StationV3Response(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    payload: StationV3
