# Auto-generated from the NS OpenAPI spec. Do not edit manually.
# To regenerate, run: uv run scripts/generate_models.sh
#
# generated by datamodel-codegen:
#   filename:  reisinformatie-api.json
#   timestamp: 2026-02-24T14:54:43+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class CheckinStep(BaseModel):
    duration: int
    type: str


class Coordinate(BaseModel):
    lat: float
    lng: float


class Eco(BaseModel):
    co2kg: float


class Reason(StrEnum):
    unknown_price = 'UNKNOWN_PRICE'
    too_many_separate_parts = 'TOO_MANY_SEPARATE_PARTS'
    too_far_in_past = 'TOO_FAR_IN_PAST'
    too_far_in_future = 'TOO_FAR_IN_FUTURE'
    station_not_open_yet = 'STATION_NOT_OPEN_YET'
    trip_is_not_domestic = 'TRIP_IS_NOT_DOMESTIC'
    via_station_requested = 'VIA_STATION_REQUESTED'
    no_train_legs_in_trip = 'NO_TRAIN_LEGS_IN_TRIP'
    non_continuous_train_legs = 'NON_CONTINUOUS_TRAIN_LEGS'


class EticketNotBuyableReason(BaseModel):
    reason: Reason
    description: str | None = None


class ProductType(StrEnum):
    train = 'TRAIN'
    bus = 'BUS'
    tram = 'TRAM'
    metro = 'METRO'
    ferry = 'FERRY'
    walk = 'WALK'
    bike = 'BIKE'
    car = 'CAR'
    taxi = 'TAXI'
    shared_modality = 'SHARED_MODALITY'
    unknown = 'UNKNOWN'


class FareLegStop(BaseModel):
    var_code: int = Field(..., alias='varCode')
    name: str | None = None


class FareRoute(BaseModel):
    route_id: str | None = Field(None, alias='routeId')
    origin: FareLegStop
    destination: FareLegStop


class Type(StrEnum):
    btm = 'BTM'
    train_xml = 'TRAIN_XML'


class Status(StrEnum):
    registration_possible = 'REGISTRATION_POSSIBLE'
    not_available = 'NOT_AVAILABLE'
    date_in_past = 'DATE_IN_PAST'
    date_too_far_future = 'DATE_TOO_FAR_FUTURE'
    not_necessary_other_operator = 'NOT_NECESSARY_OTHER_OPERATOR'
    unknown = 'UNKNOWN'


class SalesOptionType(StrEnum):
    ns_deal_discount = 'NS_DEAL_DISCOUNT'


class LabelListItem(BaseModel):
    label: str
    sticker_type: str = Field(..., alias='stickerType')
    sales_option_type: SalesOptionType | None = Field(None, alias='salesOptionType')


class TravelType(StrEnum):
    public_transit = 'PUBLIC_TRANSIT'
    walk = 'WALK'
    transfer = 'TRANSFER'
    bike = 'BIKE'
    car = 'CAR'
    kiss = 'KISS'
    taxi = 'TAXI'
    unknown = 'UNKNOWN'


class CrowdForecast(StrEnum):
    unknown = 'UNKNOWN'
    low = 'LOW'
    medium = 'MEDIUM'
    high = 'HIGH'


class ShorterStockClassification(StrEnum):
    busy = 'BUSY'
    extra_busy = 'EXTRA_BUSY'


class Link(BaseModel):
    uri: str


class MeetingPointDetails(BaseModel):
    name: str
    minutes_before: int = Field(..., alias='minutesBefore')


class Type1(StrEnum):
    maintenance = 'MAINTENANCE'
    disruption = 'DISRUPTION'
    shortened = 'SHORTENED'


class Phase(StrEnum):
    phase_1_a = 'PHASE_1A'
    phase_1_b = 'PHASE_1B'
    phase_2 = 'PHASE_2'
    phase_3 = 'PHASE_3'
    phase_4 = 'PHASE_4'
    phase_5 = 'PHASE_5'


class NesIcon(BaseModel):
    color: str
    icon: str
    background_color: str | None = Field(None, alias='backgroundColor')


class NesLineStyles(BaseModel):
    dashed: bool


class Scope(StrEnum):
    leg_line = 'LEG_LINE'
    entire_leg = 'ENTIRE_LEG'


class NesTextStyles(BaseModel):
    strikethrough: bool
    bold: bool


class NoteType(StrEnum):
    unknown = 'UNKNOWN'
    attribute = 'ATTRIBUTE'
    infotext = 'INFOTEXT'
    realtime = 'REALTIME'
    ticket = 'TICKET'
    hint = 'HINT'


class Category(StrEnum):
    platform_information = 'PLATFORM_INFORMATION'
    overcheck_instruction = 'OVERCHECK_INSTRUCTION'
    unknown = 'UNKNOWN'


class NsiLink(BaseModel):
    url: str
    """
    NSI journeyplanner url with pre-filled locations and time
    """
    show_international_banner: bool = Field(..., alias='showInternationalBanner')
    """
    Whether to display an NS International banner
    """


class Type2(StrEnum):
    trip_cancelled = 'TRIP_CANCELLED'
    leg_cancelled = 'LEG_CANCELLED'
    leg_transfer_impossible = 'LEG_TRANSFER_IMPOSSIBLE'
    alternative_transport = 'ALTERNATIVE_TRANSPORT'
    disruption = 'DISRUPTION'
    maintenance = 'MAINTENANCE'
    replacement = 'REPLACEMENT'
    additional = 'ADDITIONAL'
    shortened_train = 'SHORTENED_TRAIN'


class Type3(StrEnum):
    train = 'TRAIN'
    bus = 'BUS'
    tram = 'TRAM'
    metro = 'METRO'
    ferry = 'FERRY'
    walk = 'WALK'
    bike = 'BIKE'
    car = 'CAR'
    taxi = 'TAXI'
    shared_modality = 'SHARED_MODALITY'
    unknown = 'UNKNOWN'


class RegistrationAvailability(BaseModel):
    seats: bool
    number_of_seats: int | None = Field(None, alias='numberOfSeats')
    bicycle: bool
    number_of_bicycle_places: int | None = Field(None, alias='numberOfBicyclePlaces')


class Type4(StrEnum):
    ns_deal_discount = 'NS_DEAL_DISCOUNT'


class SalesOption(BaseModel):
    type: Type4
    permille_full_tariff: int | None = Field(None, alias='permilleFullTariff')
    price_in_cents: int | None = Field(None, alias='priceInCents')
    original_price: int | None = Field(None, alias='originalPrice')
    better_option: bool = Field(..., alias='betterOption')
    recommendation_text: str | None = Field(None, alias='recommendationText')
    label_text: str | None = Field(None, alias='labelText')


class ServiceBookingInfo(BaseModel):
    name: str
    trip_leg_index: str = Field(..., alias='tripLegIndex')
    station_uic: str | None = Field(None, alias='stationUic')
    service_type_ids: list[str] = Field(..., alias='serviceTypeIds')
    default_assistance_value: bool = Field(..., alias='defaultAssistanceValue')
    can_change_assistance: bool = Field(..., alias='canChangeAssistance')
    message: str | None = None


class NearByMeMapping(StrEnum):
    ov_fiets = 'OV_FIETS'
    shared_electrical_bike = 'SHARED_ELECTRICAL_BIKE'
    shared_bike = 'SHARED_BIKE'
    shared_scooter = 'SHARED_SCOOTER'
    shared_car = 'SHARED_CAR'
    unknown = 'UNKNOWN'


class SharedModality(BaseModel):
    provider: str
    name: str | None = None
    availability: bool
    near_by_me_mapping: NearByMeMapping = Field(..., alias='nearByMeMapping')
    plan_icon: str | None = Field(None, alias='planIcon')


class Type5(StrEnum):
    u = 'U'
    a = 'A'
    i = 'I'
    r = 'R'
    h = 'H'


class StopNote(BaseModel):
    value: str
    key: str | None = None
    type: Type5
    priority: int | None = None


class Styles(BaseModel):
    type: str


class Type6(StrEnum):
    reservation = 'RESERVATION'
    supplement = 'SUPPLEMENT'
    special_ticket = 'SPECIAL_TICKET'


class TicketAction(BaseModel):
    type: Type6
    from_uic_code: str | None = Field(None, alias='fromUicCode')
    to_uic_code: str | None = Field(None, alias='toUicCode')


class Type7(StrEnum):
    impossible_transfer = 'IMPOSSIBLE_TRANSFER'
    special = 'SPECIAL'
    checkover_instruction = 'CHECKOVER_INSTRUCTION'
    cross_platform = 'CROSS_PLATFORM'
    transfer_time = 'TRANSFER_TIME'


class Source(StrEnum):
    harp = 'HARP'
    negentwee = 'NEGENTWEE'
    google = 'GOOGLE'
    pas = 'PAS'


class TravelAssistanceInfo(BaseModel):
    terms_and_conditions_link: str | None = Field(None, alias='termsAndConditionsLink')
    trip_request_id: int = Field(..., alias='tripRequestId')
    is_assistance_required: bool = Field(..., alias='isAssistanceRequired')


class Status1(StrEnum):
    cancelled = 'CANCELLED'
    change_not_possible = 'CHANGE_NOT_POSSIBLE'
    alternative_transport = 'ALTERNATIVE_TRANSPORT'
    disruption = 'DISRUPTION'
    maintenance = 'MAINTENANCE'
    uncertain = 'UNCERTAIN'
    replacement = 'REPLACEMENT'
    additional = 'ADDITIONAL'
    special = 'SPECIAL'
    normal = 'NORMAL'


class Type8(StrEnum):
    ns = 'NS'
    ns_accessible = 'NS_ACCESSIBLE'
    negentwee = 'NEGENTWEE'
    google = 'GOOGLE'
    pas = 'PAS'


class SupplementType(StrEnum):
    icd = 'ICD'
    ice = 'ICE'


class TripFareSupplement(BaseModel):
    supplement_price_in_cents: int = Field(..., alias='supplementPriceInCents')
    from_uic_code: str | None = Field(None, alias='fromUICCode')
    to_uic_code: str | None = Field(None, alias='toUICCode')
    link: Link | None = None
    supplement_type: SupplementType | None = Field(None, alias='supplementType')


class Type9(StrEnum):
    station = 'STATION'
    address = 'ADDRESS'
    point_of_interest = 'POINT_OF_INTEREST'


class ExitSide(StrEnum):
    left = 'LEFT'
    right = 'RIGHT'
    unknown = 'UNKNOWN'


class CheckinStatus(StrEnum):
    checkin = 'CHECKIN'
    checkout = 'CHECKOUT'
    overcheck = 'OVERCHECK'
    detour = 'DETOUR'
    required_check_out_in = 'REQUIRED_CHECK_OUT_IN'
    nothing = 'NOTHING'


class Product1(StrEnum):
    ovchipkaart_enkele_reis = 'OVCHIPKAART_ENKELE_REIS'
    ovchipkaart_retour = 'OVCHIPKAART_RETOUR'
    traject_vrij_jaar = 'TRAJECT_VRIJ_JAAR'
    business_card_traject_vrij_jaar = 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR'
    eticket_enkele_reis = 'ETICKET_ENKELE_REIS'
    eticket_retour = 'ETICKET_RETOUR'
    ns_deal_discount_enkele_reis = 'NS_DEAL_DISCOUNT_ENKELE_REIS'
    railrunner = 'RAILRUNNER'
    ice_supplement = 'ICE_SUPPLEMENT'
    icd_supplement = 'ICD_SUPPLEMENT'
    nsi = 'NSI'


class TravelClass(StrEnum):
    first_class = 'FIRST_CLASS'
    second_class = 'SECOND_CLASS'


class DiscountType(StrEnum):
    no_discount = 'NO_DISCOUNT'
    discount_20_percent = 'DISCOUNT_20_PERCENT'
    discount_40_percent = 'DISCOUNT_40_PERCENT'
    no_charge = 'NO_CHARGE'
    other = 'OTHER'


class TripSalesFare(BaseModel):
    price_in_cents: int | None = Field(None, alias='priceInCents')
    product: Product1 | None = None
    travel_class: TravelClass | None = Field(None, alias='travelClass')
    price_in_cents_excluding_supplement: int | None = Field(
        None, alias='priceInCentsExcludingSupplement'
    )
    discount_type: DiscountType | None = Field(None, alias='discountType')
    supplement_in_cents: int | None = Field(None, alias='supplementInCents')
    link: str | None = None


class Product2(StrEnum):
    geen = 'GEEN'
    ovchipkaart_enkele_reis = 'OVCHIPKAART_ENKELE_REIS'
    ovchipkaart_retour = 'OVCHIPKAART_RETOUR'
    dal_voordeel = 'DAL_VOORDEEL'
    altijd_voordeel = 'ALTIJD_VOORDEEL'
    dal_vrij = 'DAL_VRIJ'
    weekend_vrij = 'WEEKEND_VRIJ'
    altijd_vrij = 'ALTIJD_VRIJ'
    businesscard = 'BUSINESSCARD'
    businesscard_dal = 'BUSINESSCARD_DAL'
    student_week = 'STUDENT_WEEK'
    student_weekend = 'STUDENT_WEEKEND'
    vdu = 'VDU'
    samenreiskorting = 'SAMENREISKORTING'
    traject_vrij = 'TRAJECT_VRIJ'


class TripTravelFare(BaseModel):
    price_in_cents: int | None = Field(None, alias='priceInCents')
    price_in_cents_excluding_supplement: int | None = Field(
        None, alias='priceInCentsExcludingSupplement'
    )
    supplement_in_cents: int | None = Field(None, alias='supplementInCents')
    buyable_ticket_price_in_cents: int | None = Field(
        None, alias='buyableTicketPriceInCents'
    )
    buyable_ticket_price_in_cents_excluding_supplement: int | None = Field(
        None, alias='buyableTicketPriceInCentsExcludingSupplement'
    )
    buyable_ticket_supplement_price_in_cents: int | None = Field(
        None, alias='buyableTicketSupplementPriceInCents'
    )
    product: Product2 | None = None
    travel_class: TravelClass | None = Field(None, alias='travelClass')
    discount_type: DiscountType = Field(..., alias='discountType')
    link: str | None = None


class LocalizedErrorDetail(BaseModel):
    message: str
    arguments: list[dict[str, Any]]
    type: str
    lang: str


class DiscountType2(StrEnum):
    none = 'NONE'
    early_booking = 'EARLY_BOOKING'
    group = 'GROUP'
    joint_journey = 'JOINT_JOURNEY'
    railrunner = 'RAILRUNNER'
    ns_deal = 'NS_DEAL'


class Unit(BaseModel):
    pass


class Type10(StrEnum):
    calamity = 'CALAMITY'
    disruption = 'DISRUPTION'
    maintenance = 'MAINTENANCE'


class BaseDisruption(BaseModel):
    id: str
    type: Type10
    is_active: bool = Field(..., alias='isActive')
    title: str
    topic: str | None = None


class NearbyMeLocationId(BaseModel):
    value: str
    type: str


class StationsNamen(BaseModel):
    lang: str
    middel: str
    kort: str
    festive: str | None = None


class Track(BaseModel):
    spoor_nummer: str = Field(..., alias='spoorNummer')


class TravelDiscount(StrEnum):
    no_discount = 'NO_DISCOUNT'
    discount_20 = 'DISCOUNT_20'
    discount_40 = 'DISCOUNT_40'
    no_charge = 'NO_CHARGE'


class TravelProduct(StrEnum):
    ovchipkaart_enkele_reis = 'OVCHIPKAART_ENKELE_REIS'
    ovchipkaart_retour = 'OVCHIPKAART_RETOUR'
    traject_vrij_jaar = 'TRAJECT_VRIJ_JAAR'
    business_card_traject_vrij_jaar = 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR'
    railrunner = 'RAILRUNNER'
    eticket_enkele_reis = 'ETICKET_ENKELE_REIS'
    eticket_retour = 'ETICKET_RETOUR'


class Price(BaseModel):
    total_price_in_cents: int = Field(..., alias='totalPriceInCents')
    price_difference_in_cents_between_first_and_second_class: int | None = Field(
        None, alias='priceDifferenceInCentsBetweenFirstAndSecondClass'
    )
    price_difference_in_cents_between_joint_journey_discount: int | None = Field(
        None, alias='priceDifferenceInCentsBetweenJointJourneyDiscount'
    )
    operator_name: str | None = Field(None, alias='operatorName')
    travel_discount: TravelDiscount = Field(..., alias='travelDiscount')
    travel_class: TravelClass = Field(..., alias='travelClass')
    travel_products: list[TravelProduct] = Field(..., alias='travelProducts')


class RepresentationResponsePrice(BaseModel):
    payload: Price
    links: dict[str, Link] | None = None
    meta: dict[str, Any] | None = None  # patched: API returns flat dict, not nested


class Classification(StrEnum):
    unknown = 'UNKNOWN'
    low = 'LOW'
    medium = 'MEDIUM'
    high = 'HIGH'


class CoachCrowdForecast(BaseModel):
    padding_left: int = Field(..., alias='paddingLeft')
    width: int
    classification: Classification


class Status2(StrEnum):
    origin = 'ORIGIN'
    split = 'SPLIT'
    stop = 'STOP'
    passing = 'PASSING'
    combine = 'COMBINE'
    destination = 'DESTINATION'
    stop_changed_origin = 'STOP_CHANGED_ORIGIN'
    stop_changed_destination = 'STOP_CHANGED_DESTINATION'


class Kind(StrEnum):
    departure = 'DEPARTURE'
    arrival = 'ARRIVAL'
    transfer = 'TRANSFER'


class PlatformFeature(BaseModel):
    padding_left: int = Field(..., alias='paddingLeft')
    width: int
    type: str
    description: str


class StockPartLink(BaseModel):
    uri: str


class DepartureStatus(StrEnum):
    on_station = 'ON_STATION'
    incoming = 'INCOMING'
    departed = 'DEPARTED'
    unknown = 'UNKNOWN'


class RouteStation(BaseModel):
    uic_code: str | None = Field(None, alias='uicCode')
    medium_name: str | None = Field(None, alias='mediumName')


class ArrivalStatus(StrEnum):
    on_station = 'ON_STATION'
    incoming = 'INCOMING'
    departed = 'DEPARTED'
    unknown = 'UNKNOWN'


class Type11(StrEnum):
    informatie = 'informatie'
    waarschuwing = 'waarschuwing'


class ButtonPositie(StrEnum):
    boven = 'boven'
    onder = 'onder'
    beide = 'beide'


class Type12(StrEnum):
    button__primary = 'button--primary'
    button__secondary = 'button--secondary'
    button__buy = 'button--buy'
    button__print = 'button--print'


class CallToActionButton(BaseModel):
    call_to_action: str | None = Field(None, alias='callToAction')
    url: str | None = None
    type: Type12 | None = None
    voorleestitel: str | None = None


class DownloadFile(BaseModel):
    url: str | None = None
    length: int | None = None
    mime_type: str | None = Field(None, alias='mimeType')
    last_modified: int | None = Field(None, alias='lastModified')


class JourneyDetailLink(BaseModel):
    type: Type
    link: Link


class JourneyRegistrationParameters(BaseModel):
    url: AnyUrl | None = None
    search_url: AnyUrl = Field(..., alias='searchUrl')
    status: Status
    bicycle_reservation_required: bool = Field(..., alias='bicycleReservationRequired')
    availability: RegistrationAvailability | None = None


class NesLine(BaseModel):
    color: str
    styles: NesLineStyles | None = None


class NesProperties(BaseModel):
    color: str
    type: str | None = None
    icon: str | None = None
    scope: Scope | None = None
    styles: Styles | None = None  # discriminator removed: Styles is not a union type


class NesText(BaseModel):
    color: str
    text: str
    accessibility_text: str = Field(..., alias='accessibilityText')
    background_color: str | None = Field(None, alias='backgroundColor')
    styles: NesTextStyles | None = None


class Note(BaseModel):
    value: str | None = None
    short_value: str | None = Field(None, alias='shortValue')
    accessibility_value: str | None = Field(None, alias='accessibilityValue')
    key: str | None = None
    note_type: NoteType | None = Field(None, alias='noteType')
    priority: int | None = None
    route_idx_from: int | None = Field(None, alias='routeIdxFrom')
    route_idx_to: int | None = Field(None, alias='routeIdxTo')
    link: Link | None = None
    is_presentation_required: bool = Field(..., alias='isPresentationRequired')
    category: Category | None = None
    nes_properties: NesProperties | None = Field(None, alias='nesProperties')


class ProductInterface(BaseModel):
    type: Type3
    number: str | None = None
    display_name: str | None = Field(None, alias='displayName')
    operator_code: str | None = Field(None, alias='operatorCode')
    notes: list[list[Note]] | None = None  # patched: not always returned by the API
    operator_name: str | None = Field(None, alias='operatorName')
    name_nes_properties: NesProperties | None = Field(None, alias='nameNesProperties')  # patched: not always returned by the API
    icon_nes_properties: NesProperties | None = Field(None, alias='iconNesProperties')
    short_category_name: str | None = Field(None, alias='shortCategoryName')
    category_code: str | None = Field(None, alias='categoryCode')
    long_category_name: str | None = Field(None, alias='longCategoryName')
    operator_administrative_code: int | None = Field(
        None, alias='operatorAdministrativeCode'
    )
    product_type: str | None = Field(None, alias='productType')  # patched: not always returned by the API


class Step(BaseModel):
    text: NesText
    duration: NesText | None = None
    icon: NesIcon | None = None
    line: NesLine


class Stop(BaseModel):
    uic_code: str | None = Field(None, alias='uicCode')
    uic_cd_code: str | None = Field(None, alias='uicCdCode')
    name: str | None = None
    lat: float | None = None
    lng: float | None = None
    country_code: str | None = Field(None, alias='countryCode')
    notes: list[StopNote]
    route_idx: int | None = Field(None, alias='routeIdx')
    departure_prognosis_type: str | None = Field(None, alias='departurePrognosisType')
    planned_departure_date_time: AwareDatetime | None = Field(
        None, alias='plannedDepartureDateTime'
    )
    planned_departure_time_zone_offset: int | None = Field(
        None, alias='plannedDepartureTimeZoneOffset'
    )
    actual_departure_date_time: AwareDatetime | None = Field(
        None, alias='actualDepartureDateTime'
    )
    actual_departure_time_zone_offset: int | None = Field(
        None, alias='actualDepartureTimeZoneOffset'
    )
    planned_arrival_date_time: AwareDatetime | None = Field(
        None, alias='plannedArrivalDateTime'
    )
    planned_arrival_time_zone_offset: int | None = Field(
        None, alias='plannedArrivalTimeZoneOffset'
    )
    actual_arrival_date_time: AwareDatetime | None = Field(
        None, alias='actualArrivalDateTime'
    )
    actual_arrival_time_zone_offset: int | None = Field(
        None, alias='actualArrivalTimeZoneOffset'
    )
    planned_passing_date_time: AwareDatetime | None = Field(
        None, alias='plannedPassingDateTime'
    )
    actual_passing_date_time: AwareDatetime | None = Field(
        None, alias='actualPassingDateTime'
    )
    arrival_prognosis_type: str | None = Field(None, alias='arrivalPrognosisType')
    actual_departure_track: str | None = Field(None, alias='actualDepartureTrack')
    planned_departure_track: str | None = Field(None, alias='plannedDepartureTrack')
    planned_arrival_track: str | None = Field(None, alias='plannedArrivalTrack')
    actual_arrival_track: str | None = Field(None, alias='actualArrivalTrack')
    departure_delay_in_seconds: int | None = Field(
        None, alias='departureDelayInSeconds'
    )
    arrival_delay_in_seconds: int | None = Field(None, alias='arrivalDelayInSeconds')
    cancelled: bool
    border_stop: bool = Field(..., alias='borderStop')
    passing: bool
    quay_code: str | None = Field(None, alias='quayCode')


class TransferMessage(BaseModel):
    message: str
    accessibility_message: str = Field(..., alias='accessibilityMessage')
    type: Type7
    message_nes_properties: NesProperties = Field(..., alias='messageNesProperties')
    icon_nes_properties: NesProperties | None = Field(None, alias='iconNesProperties')


class TravelAdviceMessage(BaseModel):
    title: str
    nes_properties: NesProperties = Field(..., alias='nesProperties')
    disruption_ids: list[str] = Field(..., alias='disruptionIds')


class TripFareOptions(BaseModel):
    is_international_bookable: bool = Field(..., alias='isInternationalBookable')
    is_international: bool = Field(..., alias='isInternational')
    is_eticket_buyable: bool = Field(..., alias='isEticketBuyable')
    is_possible_with_ov_chipkaart: bool = Field(..., alias='isPossibleWithOvChipkaart')
    is_total_price_unknown: bool = Field(..., alias='isTotalPriceUnknown')
    supplements_based_on_selected_fare: list[TripFareSupplement] | None = Field(
        None, alias='supplementsBasedOnSelectedFare'
    )
    reason_eticket_not_buyable: EticketNotBuyableReason | None = Field(
        None, alias='reasonEticketNotBuyable'
    )
    sales_options: list[SalesOption] | None = Field(None, alias='salesOptions')


class TripOriginDestination(BaseModel):
    name: str | None = None
    raw_location_name: str | None = Field(None, alias='rawLocationName')
    """
    The raw location name is the same as the name, except it excluded prefixes such as bushalte/metrohalte/etc. and it excludes emojis
    """
    lng: float | None = None
    lat: float | None = None
    city: str | None = None
    country_code: str | None = Field(None, alias='countryCode')
    uic_code: str | None = Field(None, alias='uicCode')
    uic_cd_code: str | None = Field(None, alias='uicCdCode')
    station_code: str | None = Field(None, alias='stationCode')
    type: Type9 | None = None
    prognosis_type: str | None = Field(None, alias='prognosisType')
    planned_time_zone_offset: int | None = Field(None, alias='plannedTimeZoneOffset')
    planned_date_time: AwareDatetime | None = Field(None, alias='plannedDateTime')
    actual_time_zone_offset: int | None = Field(None, alias='actualTimeZoneOffset')
    actual_date_time: AwareDatetime | None = Field(None, alias='actualDateTime')
    planned_track: str | None = Field(None, alias='plannedTrack')
    actual_track: str | None = Field(None, alias='actualTrack')
    exit_side: ExitSide | None = Field(None, alias='exitSide')
    checkin_status: CheckinStatus | None = Field(None, alias='checkinStatus')
    travel_assistance_booking_info: ServiceBookingInfo | None = Field(
        None, alias='travelAssistanceBookingInfo'
    )
    travel_assistance_meeting_points: list[str] | None = Field(
        None, alias='travelAssistanceMeetingPoints'
    )
    travel_assistance_meeting_point_details: list[MeetingPointDetails] | None = Field(
        None, alias='travelAssistanceMeetingPointDetails'
    )
    notes: list[Note] | None = None
    quay_code: str | None = Field(None, alias='quayCode')


class APIError(BaseModel):
    timestamp: AwareDatetime
    code: int
    message: str
    path: str
    exception: str | None = None
    errors: list[LocalizedErrorDetail] | None = None
    request_id: str = Field(..., alias='requestId')


class PriceV3(BaseModel):
    total_price_in_cents: int = Field(..., alias='totalPriceInCents')
    """
    Total price
    """
    price_per_adult_in_cents: int = Field(..., alias='pricePerAdultInCents')
    """
    Price per adult
    """
    discount_in_cents: int | None = Field(None, alias='discountInCents')
    """
    Discount price compared to total price without any discount
    """
    operator_name: str | None = Field(None, alias='operatorName')
    """
    Name of the operator
    """
    discount_type: DiscountType2 = Field(..., alias='discountType')
    """
    Type of discount
    """
    travel_class: TravelClass = Field(..., alias='travelClass')
    """
    Traveling class
    """
    travel_products: list[Unit] = Field(..., alias='travelProducts')
    """
    Travel products types
    """
    is_selectable: bool = Field(..., alias='isSelectable')
    """
    Denotes if the user can select this option
    """
    display_name: str = Field(..., alias='displayName')
    """
    Display name of product
    """
    conditions_header: str = Field(..., alias='conditionsHeader')
    """
    Header of conditions
    """
    conditions_text: str | None = Field(None, alias='conditionsText')
    """
    Conditions of product
    """
    conditions_url: str | None = Field(None, alias='conditionsUrl')
    """
    Url to webpage with common conditions
    """
    product_id: str = Field(..., alias='productId')
    """
    Product ID used to buy ticket
    """
    is_best_option: bool = Field(..., alias='isBestOption')
    """
    Indicates if this price is the best option for client
    """
    price_per_child_in_cents: int = Field(..., alias='pricePerChildInCents')
    """
    Price per child
    """


class PricesResponseV3(BaseModel):
    prices: list[PriceV3]


class RepresentationResponsePricesResponseV3(BaseModel):
    payload: PricesResponseV3
    links: dict[str, Link] | None = None
    meta: dict[str, Any] | None = None  # patched: API returns flat dict, not nested


class Station(BaseModel):
    uic_code: str | None = Field(None, alias='UICCode')  # patched: not always returned
    uic_cd_code: str | None = Field(None, alias='UICCdCode')
    station_type: str | None = Field(None, alias='stationType')  # patched: not always returned
    eva_code: str | None = Field(None, alias='EVACode')
    code: str | None = None
    cd_code: int | None = Field(None, alias='cdCode')
    sporen: list[Track] | None = None  # patched: not always returned
    synoniemen: list[str] | None = None  # patched: not always returned
    heeft_faciliteiten: bool | None = Field(None, alias='heeftFaciliteiten')  # patched: not always returned
    heeft_vertrektijden: bool | None = Field(None, alias='heeftVertrektijden')  # patched: not always returned
    heeft_reisassistentie: bool | None = Field(None, alias='heeftReisassistentie')  # patched: not always returned
    namen: StationsNamen | None = None
    land: str | None = None
    lat: float | None = None
    lng: float | None = None
    radius: int | None = None
    naderen_radius: int | None = Field(None, alias='naderenRadius')
    distance: float | None = None
    ingangs_datum: date | None = Field(None, alias='ingangsDatum')
    eind_datum: date | None = Field(None, alias='eindDatum')
    nearby_me_location_id: NearbyMeLocationId | None = Field(
        None, alias='nearbyMeLocationId'
    )


class StationResponse(BaseModel):
    payload: list[Station]
    links: dict[str, str] | None = None
    meta: dict[str, str] | None = None


class Part(BaseModel):
    stock_identifier: str | None = Field(None, alias='stockIdentifier')
    destination: Station | None = None
    facilities: list[str]
    image: StockPartLink | None = None


class Stock(BaseModel):
    train_type: str | None = Field(None, alias='trainType')
    number_of_seats: int = Field(..., alias='numberOfSeats')
    number_of_parts: int = Field(..., alias='numberOfParts')
    train_parts: list[Part] = Field(..., alias='trainParts')
    has_significant_change: bool = Field(..., alias='hasSignificantChange')


class Download(BaseModel):
    titel: str | None = None
    bestand: DownloadFile | None = None


class Duration(BaseModel):
    value: str
    accessibility_value: str = Field(..., alias='accessibilityValue')
    nes_properties: NesProperties = Field(..., alias='nesProperties')


class FareLeg(BaseModel):
    origin: TripOriginDestination
    destination: TripOriginDestination
    operator: str | None = None
    product_types: list[ProductType] = Field(..., alias='productTypes')
    fares: list[TripTravelFare]
    travel_date: date | None = Field(None, alias='travelDate')


class Message(BaseModel):
    id: str | None = None
    external_id: str | None = Field(None, alias='externalId')
    head: str | None = None
    text: str | None = None
    lead: str | None = None
    route_idx_from: int | None = Field(None, alias='routeIdxFrom')
    route_idx_to: int | None = Field(None, alias='routeIdxTo')
    type: Type1 | None = None
    nes_properties: NesProperties | None = Field(None, alias='nesProperties')
    start_date: str | None = Field(None, alias='startDate')
    end_date: str | None = Field(None, alias='endDate')
    start_time: str | None = Field(None, alias='startTime')
    end_time: str | None = Field(None, alias='endTime')
    phase: Phase | None = None


class ModalityListItem(BaseModel):
    name: str
    name_nes_properties: NesProperties = Field(..., alias='nameNesProperties')
    icon_nes_properties: NesProperties | None = Field(None, alias='iconNesProperties')
    actual_track: str | None = Field(None, alias='actualTrack')
    accessibility_name: str = Field(..., alias='accessibilityName')


class PrimaryMessage(BaseModel):
    title: str
    nes_properties: NesProperties = Field(..., alias='nesProperties')
    message: Message | None = None
    type: Type2


class Product(ProductInterface):
    notes: list[list[Note]] | None = None  # patched: not always returned by the API
    """
    notes is a List of Lists because this allows frontend clients to render the elements of every nested List on the same row
    """
    nes_properties: NesProperties | None = Field(None, alias='nesProperties')
    name_nes_properties: NesProperties | None = Field(None, alias='nameNesProperties')  # patched: not always returned by the API
    type: Type3
    product_type: Literal['Product'] | None = Field(None, alias='productType')  # patched: not always returned by the API


class ArrivalOrDeparture(BaseModel):
    product: Product
    origin: Station | None = None
    destination: Station | None = None
    planned_time: AwareDatetime | None = Field(None, alias='plannedTime')
    actual_time: AwareDatetime | None = Field(None, alias='actualTime')
    delay_in_seconds: int | None = Field(None, alias='delayInSeconds')
    planned_track: str | None = Field(None, alias='plannedTrack')
    actual_track: str | None = Field(None, alias='actualTrack')
    cancelled: bool
    punctuality: float | None = None
    crowd_forecast: CrowdForecast = Field(..., alias='crowdForecast')
    shorter_stock_classification: ShorterStockClassification | None = Field(
        None, alias='shorterStockClassification'
    )
    stock_identifiers: list[str] | None = Field(None, alias='stockIdentifiers')


class JourneyStop(BaseModel):
    id: str
    stop: Station
    previous_stop_id: list[str] = Field(..., alias='previousStopId')
    next_stop_id: list[str] = Field(..., alias='nextStopId')
    destination: str | None = None
    status: Status2 | None = None
    kind: Kind | None = None
    arrivals: list[ArrivalOrDeparture]
    departures: list[ArrivalOrDeparture]
    actual_stock: Stock | None = Field(None, alias='actualStock')
    planned_stock: Stock | None = Field(None, alias='plannedStock')
    platform_features: list[PlatformFeature] | None = Field(
        None, alias='platformFeatures'
    )
    coach_crowd_forecast: list[CoachCrowdForecast] | None = Field(
        None, alias='coachCrowdForecast'
    )


class Departure(BaseModel):
    direction: str | None = None
    name: str
    planned_date_time: AwareDatetime | None = Field(None, alias='plannedDateTime')
    planned_time_zone_offset: int | None = Field(None, alias='plannedTimeZoneOffset')
    actual_date_time: AwareDatetime | None = Field(None, alias='actualDateTime')
    actual_time_zone_offset: int | None = Field(None, alias='actualTimeZoneOffset')
    planned_track: str | None = Field(None, alias='plannedTrack')
    actual_track: str | None = Field(None, alias='actualTrack')
    product: Product
    train_category: str = Field(..., alias='trainCategory')
    cancelled: bool
    journey_detail_ref: str | None = Field(None, alias='journeyDetailRef')
    route_stations: list[RouteStation] = Field(..., alias='routeStations')
    messages: list[Message]
    departure_status: DepartureStatus = Field(..., alias='departureStatus')


class DeparturesPayload(BaseModel):
    source: str
    departures: list[Departure]


class RepresentationResponseDeparturesPayload(BaseModel):
    payload: DeparturesPayload
    links: dict[str, Link] | None = None
    meta: dict[str, Any] | None = None  # patched: API returns flat dict, not nested


class Arrival(BaseModel):
    origin: str | None = None
    name: str
    planned_date_time: AwareDatetime | None = Field(None, alias='plannedDateTime')
    planned_time_zone_offset: int | None = Field(None, alias='plannedTimeZoneOffset')
    actual_date_time: AwareDatetime | None = Field(None, alias='actualDateTime')
    actual_time_zone_offset: int | None = Field(None, alias='actualTimeZoneOffset')
    planned_track: str | None = Field(None, alias='plannedTrack')
    actual_track: str | None = Field(None, alias='actualTrack')
    product: Product
    train_category: str = Field(..., alias='trainCategory')
    cancelled: bool
    journey_detail_ref: str | None = Field(None, alias='journeyDetailRef')
    messages: list[Message]
    arrival_status: ArrivalStatus = Field(..., alias='arrivalStatus')


class ArrivalsPayload(BaseModel):
    source: str
    arrivals: list[Arrival]


class RepresentationResponseArrivalsPayload(BaseModel):
    payload: ArrivalsPayload
    links: dict[str, Link] | None = None
    meta: dict[str, Any] | None = None  # patched: API returns flat dict, not nested


class CalamityBodyItem(BaseModel):
    object_type: str = Field(..., alias='objectType')
    content: str | None = None
    titel: str | None = None
    downloads: list[Download] | None = None
    links: list[Link] | None = None


class Leg(BaseModel):
    idx: str | None = None
    name: str | None = None
    travel_type: TravelType | None = Field(None, alias='travelType')
    direction: str | None = None
    part_cancelled: bool = Field(..., alias='partCancelled')
    cancelled: bool
    is_after_cancelled_leg: bool = Field(..., alias='isAfterCancelledLeg')
    is_on_or_after_cancelled_leg: bool = Field(..., alias='isOnOrAfterCancelledLeg')
    change_possible: bool = Field(..., alias='changePossible')
    alternative_transport: bool = Field(..., alias='alternativeTransport')
    journey_detail_ref: str | None = Field(None, alias='journeyDetailRef')
    origin: TripOriginDestination
    destination: TripOriginDestination
    product: Product | None = None  # discriminator removed: Product is not a union type
    shared_modality: SharedModality | None = Field(None, alias='sharedModality')
    notes: list[Note] | None = None
    messages: list[Message] | None = None
    transfer_messages: list[TransferMessage] | None = Field(
        None, alias='transferMessages'
    )
    stops: list[Stop]
    steps: list[Step] | None = None
    coordinates: list[list[float]] | None = None
    crowd_forecast: CrowdForecast | None = Field(None, alias='crowdForecast')
    bicycle_spot_count: int | None = Field(None, alias='bicycleSpotCount')
    punctuality: float | None = None
    cross_platform_transfer: bool | None = Field(None, alias='crossPlatformTransfer')
    shorter_stock: bool | None = Field(None, alias='shorterStock')
    change_could_be_possible: bool | None = Field(None, alias='changeCouldBePossible')
    shorter_stock_warning: str | None = Field(None, alias='shorterStockWarning')
    shorter_stock_classification: ShorterStockClassification | None = Field(
        None, alias='shorterStockClassification'
    )
    journey_detail: list[JourneyDetailLink] | None = Field(None, alias='journeyDetail')
    reachable: bool
    planned_duration_in_minutes: int | None = Field(
        None, alias='plannedDurationInMinutes'
    )
    actual_duration_in_minutes: int | None = Field(
        None, alias='actualDurationInMinutes'
    )
    travel_assistance_departure: ServiceBookingInfo | None = Field(
        None, alias='travelAssistanceDeparture'
    )
    travel_assistance_arrival: ServiceBookingInfo | None = Field(
        None, alias='travelAssistanceArrival'
    )
    overview_poly_line: list[Coordinate] | None = Field(None, alias='overviewPolyLine')
    nes_properties: NesProperties | None = Field(None, alias='nesProperties')
    duration: Duration | None = None
    pre_steps: list[Step] = Field(..., alias='preSteps')
    post_steps: list[Step] = Field(..., alias='postSteps')
    transfer_time_to_next_leg: int | None = Field(None, alias='transferTimeToNextLeg')
    checkin_step: CheckinStep | None = Field(None, alias='checkinStep')
    recognizable_destination: str | None = Field(None, alias='recognizableDestination')
    distance_in_meters: int | None = Field(None, alias='distanceInMeters')
    ticket_actions: list[TicketAction] | None = Field(None, alias='ticketActions')
    minimally_added_change_time: int | None = Field(
        None, alias='minimallyAddedChangeTime'
    )


class Trip(BaseModel):
    uid: str
    """
    Unique identifier for this trip
    """
    ctx_recon: str = Field(..., alias='ctxRecon')
    """
    Reconstruction context for this trip. Can be used to reconstruct this exact trip with the v3/trips/trip endpoint
    """
    source_ctx_recon: str | None = Field(None, alias='sourceCtxRecon')
    """
    Reconstruction context for this trip set by the travel advice source system. Can be used to interact follow-up requests with the source system, like booking a trip with travel assistance (NSRA). Can be null if the source doesn't provide a ctxRecon
    """
    planned_duration_in_minutes: int | None = Field(
        None, alias='plannedDurationInMinutes'
    )
    """
    Planned duration of this trip in minutes
    """
    actual_duration_in_minutes: int | None = Field(
        None, alias='actualDurationInMinutes'
    )
    """
    Actual duration of this trip in minutes, or the planned duration if no realtime information about this trip is available.
    """
    transfers: int
    """
    Number of public transit transfers
    """
    status: Status1
    """
    Status of this trip
    """
    primary_message: PrimaryMessage | None = Field(None, alias='primaryMessage')
    messages: list[Message] | None = None
    """
    List of messages regarding maintenance or disruption that influences this trip.
    """
    legs: list[Leg]
    overview_poly_line: list[Coordinate] | None = Field(None, alias='overviewPolyLine')
    crowd_forecast: CrowdForecast | None = Field(None, alias='crowdForecast')
    punctuality: float | None = None
    optimal: bool
    """
    Whether or not this trip is regarded the best possible option of all returned trips
    """
    fare_route: FareRoute | None = Field(None, alias='fareRoute')
    fares: list[TripSalesFare] | None = None
    fare_legs: list[FareLeg] | None = Field(None, alias='fareLegs')
    product_fare: TripTravelFare | None = Field(None, alias='productFare')
    fare_options: TripFareOptions | None = Field(None, alias='fareOptions')
    booking_url: Link | None = Field(None, alias='bookingUrl')
    nsi_link: NsiLink | None = Field(None, alias='nsiLink')
    type: Type8
    share_url: Link | None = Field(None, alias='shareUrl')
    realtime: bool
    travel_assistance_info: TravelAssistanceInfo | None = Field(
        None, alias='travelAssistanceInfo'
    )
    route_id: str | None = Field(None, alias='routeId')
    register_journey: JourneyRegistrationParameters | None = Field(
        None, alias='registerJourney'
    )
    eco: Eco | None = None
    modality_list_items: list[ModalityListItem] | None = Field(
        None, alias='modalityListItems'
    )
    label_list_items: list[LabelListItem] | None = Field(None, alias='labelListItems')


class Journey(BaseModel):
    notes: list[Note]
    product_numbers: list[str] = Field(..., alias='productNumbers')
    stops: list[JourneyStop]
    allow_crowd_reporting: bool = Field(..., alias='allowCrowdReporting')
    source: str


class RepresentationResponseJourney(BaseModel):
    payload: Journey
    links: dict[str, Link] | None = None
    meta: dict[str, Any] | None = None  # patched: API returns flat dict, not nested


class CalamitiesResourceCalamity(BaseModel):
    id: str | None = None
    titel: str | None = None
    beschrijving: str | None = None
    last_modified: int | None = Field(None, alias='lastModified')
    type: Type11 | None = None
    url: str | None = None
    button_positie: ButtonPositie | None = Field(None, alias='buttonPositie')
    laatst_gewijzigd: int | None = Field(None, alias='laatstGewijzigd')
    volgende_update: int | None = Field(None, alias='volgendeUpdate')
    calltoactionbuttons: list[CallToActionButton] | None = None
    bodyitems: list[CalamityBodyItem] | None = None


class CalamitiesResponse(BaseModel):
    calamiteit: CalamitiesResourceCalamity | None = None
    meldingen: list[CalamitiesResourceCalamity] | None = None


class TravelAdvice(BaseModel):
    source: Source
    """
    Source system that has generated these travel advices
    """
    trips: list[Trip]
    """
    List of trips
    """
    travel_advice_message: TravelAdviceMessage | None = Field(
        None, alias='travelAdviceMessage'
    )
    scroll_request_backward_context: str | None = Field(
        None, alias='scrollRequestBackwardContext'
    )
    """
    Scroll context to use when scrolling back in time. Can be used in scrollContext query parameter
    """
    scroll_request_forward_context: str | None = Field(
        None, alias='scrollRequestForwardContext'
    )
    """
    Scroll context to use when scrolling forward in time. Can be used in scrollContext query parameter
    """
    message: str | None = None
    """
    Optional message indicating why the list of trips is empty.
    """
